//! User configuration, persisted as JSON.

use std::path::PathBuf;

use serde::{Deserialize, Serialize};

use crate::{paths::Paths, Error, Result};

/// Which Wine build to prefer. The fallback chain can still try others.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
#[derive(Default)]
pub enum WineVariant {
    /// WineHQ stable.
    #[default]
    Stable,
    /// WineHQ staging, carries experimental patches.
    Staging,
    /// A `wine-tkg` build such as the ones Lutris ships.
    Build(String),
    /// Whatever `wine` resolves to on `$PATH`.
    System,
}

impl WineVariant {
    pub fn label(&self) -> &str {
        match self {
            WineVariant::Stable => "stable",
            WineVariant::Staging => "staging",
            WineVariant::Build(name) => name,
            WineVariant::System => "system",
        }
    }
}

/// How aggressively to confine a Wine prefix.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
#[derive(Default)]
pub enum SandboxMode {
    /// Run Wine directly. Fastest, least isolation.
    Off,
    /// Run under bubblewrap with read-only system mounts and no access to the
    /// rest of `$HOME`. Requires the `bubblewrap` package.
    #[default]
    Strict,
}

/// A one-click trade-off between frame pacing, raw throughput and correctness.
///
/// The mode supplies defaults; anything the user sets explicitly in
/// [`DxvkSettings`] is applied on top, so the two never fight.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum PerformanceMode {
    /// Ship with whatever the application asks for.
    #[default]
    Balanced,
    /// Minimise input latency: one frame queued, no cap, shader cache on.
    Performance,
    /// Favour correctness for applications that misbehave with a modern
    /// presentation path.
    Compatibility,
}

impl PerformanceMode {
    pub fn label(self) -> &'static str {
        match self {
            PerformanceMode::Balanced => "Balanced",
            PerformanceMode::Performance => "Performance",
            PerformanceMode::Compatibility => "Compatibility",
        }
    }

    pub fn description(self) -> &'static str {
        match self {
            PerformanceMode::Balanced => "Let each application choose (recommended)",
            PerformanceMode::Performance => {
                "Lowest input latency; may stutter on very new GPU drivers"
            }
            PerformanceMode::Compatibility => {
                "Trade some latency for correctness in older or unusual applications"
            }
        }
    }

    pub fn preset(self) -> DxvkSettings {
        match self {
            PerformanceMode::Balanced => DxvkSettings::default(),
            PerformanceMode::Performance => DxvkSettings {
                hud: String::new(),
                max_frame_rate: 0,
                max_frame_latency: 1,
                compiler_threads: 0,
                sync_interval: -1,
                graphics_pipeline_library: true,
            },
            PerformanceMode::Compatibility => DxvkSettings {
                hud: String::new(),
                max_frame_rate: 60,
                max_frame_latency: 0,
                compiler_threads: 0,
                sync_interval: 1,
                graphics_pipeline_library: false,
            },
        }
    }
}

/// Per-application DXVK tuning, rendered into `dxvk.conf` and `DXVK_*` vars.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default)]
pub struct DxvkSettings {
    /// `DXVK_HUD` contents, e.g. `fps,devinfo`. Empty disables the HUD.
    pub hud: String,
    /// Frame-rate cap. `0` means uncapped.
    pub max_frame_rate: u32,
    /// `d3d9.maxFrameLatency` / `dxgi.maxFrameLatency`. `0` keeps defaults.
    pub max_frame_latency: u32,
    /// `dxvk.numCompilerThreads`. `0` lets DXVK decide.
    pub compiler_threads: u32,
    /// `dxgi.syncInterval`; `-1` lets the application choose.
    pub sync_interval: i32,
    /// `dxvk.enableGraphicsPipelineLibrary` — faster first-run shader compile.
    pub graphics_pipeline_library: bool,
}

impl Default for DxvkSettings {
    fn default() -> Self {
        DxvkSettings {
            hud: String::new(),
            max_frame_rate: 0,
            max_frame_latency: 0,
            compiler_threads: 0,
            sync_interval: -1,
            graphics_pipeline_library: true,
        }
    }
}

impl DxvkSettings {
    /// Render the `dxvk.conf` body for these settings.
    pub fn to_conf(&self) -> String {
        let mut out =
            String::from("# Generated by WinDrop. Edit via the application's settings pane.\n");
        if self.max_frame_rate > 0 {
            out.push_str(&format!("d3d9.maxFrameRate = {}\n", self.max_frame_rate));
            out.push_str(&format!("dxgi.maxFrameRate = {}\n", self.max_frame_rate));
        }
        if self.max_frame_latency > 0 {
            out.push_str(&format!(
                "d3d9.maxFrameLatency = {}\n",
                self.max_frame_latency
            ));
            out.push_str(&format!(
                "dxgi.maxFrameLatency = {}\n",
                self.max_frame_latency
            ));
        }
        if self.compiler_threads > 0 {
            out.push_str(&format!(
                "dxvk.numCompilerThreads = {}\n",
                self.compiler_threads
            ));
        }
        if self.sync_interval >= 0 {
            out.push_str(&format!("dxgi.syncInterval = {}\n", self.sync_interval));
        }
        out.push_str(&format!(
            "dxvk.enableGraphicsPipelineLibrary = {}\n",
            if self.graphics_pipeline_library {
                "True"
            } else {
                "False"
            }
        ));
        out
    }

    /// Environment variables implied by these settings.
    pub fn to_env(&self) -> Vec<(String, String)> {
        let mut vars = Vec::new();
        if !self.hud.is_empty() {
            vars.push(("DXVK_HUD".to_string(), self.hud.clone()));
        }
        if self.max_frame_rate > 0 {
            vars.push((
                "DXVK_FRAME_RATE".to_string(),
                self.max_frame_rate.to_string(),
            ));
        }
        if !self.graphics_pipeline_library {
            vars.push((
                "DXVK_CONFIG".to_string(),
                "dxvk.enableGraphicsPipelineLibrary = False".to_string(),
            ));
        }
        vars
    }
}

/// Top-level configuration.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default)]
pub struct Config {
    /// Preferred Wine build.
    pub wine_variant: WineVariant,
    /// Enable the DXVK Direct3D 9/10/11 translation layer.
    pub dxvk: bool,
    /// Enable VKD3D-Proton for Direct3D 12.
    pub vkd3d_proton: bool,
    /// Wine `esync` (eventfd-based synchronisation).
    pub esync: bool,
    /// Wine `fsync` (futex-based, faster but needs a patched kernel).
    pub fsync: bool,
    /// Prefix confinement strategy.
    pub sandbox: SandboxMode,
    /// Host directories exposed read-write inside the sandbox.
    pub shared_folders: Vec<PathBuf>,
    /// Allow WinDrop to fetch/refresh profiles from the registry.
    pub allow_remote_registry: bool,
    /// Download a newer compatibility profile when one appears.
    pub auto_profile_updates: bool,
    /// Remote registry endpoint returning profile JSON.
    pub registry_url: String,
    /// Opt-in anonymous diagnostics. Off by default and never required.
    pub telemetry: bool,
    /// Override for the data directory; `None` uses the XDG default.
    pub data_dir: Option<PathBuf>,
    /// How long an installer may run before it is killed.
    pub install_timeout_secs: u64,
    /// `tracing` filter directive.
    pub log_level: String,
    /// Ask the user to pick the main executable instead of guessing.
    pub prompt_for_main_exe: bool,
    /// Drive installers with their silent flags instead of showing them.
    ///
    /// Off by default: most installers ask at least one question, and answering
    /// it takes seconds where guessing goes wrong quietly. Someone installing a
    /// batch of well-behaved applications may prefer the other trade-off.
    pub install_silently: bool,
    /// Explicit DXVK tuning, applied over the performance-mode preset.
    pub dxvk_settings: DxvkSettings,
    /// One-click performance trade-off.
    pub performance_mode: PerformanceMode,
}

impl Default for Config {
    fn default() -> Self {
        Config {
            wine_variant: WineVariant::default(),
            dxvk: true,
            vkd3d_proton: true,
            esync: true,
            fsync: false,
            sandbox: SandboxMode::default(),
            shared_folders: Vec::new(),
            allow_remote_registry: true,
            auto_profile_updates: true,
            registry_url:
                "https://raw.githubusercontent.com/windrop/windrop/main/registry/profiles.json"
                    .to_string(),
            telemetry: false,
            data_dir: None,
            install_timeout_secs: 3600,
            log_level: "info".to_string(),
            prompt_for_main_exe: false,
            install_silently: false,
            dxvk_settings: DxvkSettings::default(),
            performance_mode: PerformanceMode::default(),
        }
    }
}

impl Config {
    /// Load configuration, returning defaults when the file does not exist.
    ///
    /// A *corrupt* file is an error rather than a silent reset, so a typo never
    /// silently discards a user's settings.
    pub fn load(path: &std::path::Path) -> Result<Self> {
        match std::fs::read_to_string(path) {
            Ok(text) => {
                let cfg: Config = serde_json::from_str(&text)?;
                cfg.validate()?;
                Ok(cfg)
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Config::default()),
            Err(e) => Err(Error::Io(e)),
        }
    }

    /// Load from the standard config location.
    pub fn load_default(paths: &Paths) -> Result<Self> {
        Config::load(&paths.config_file())
    }

    /// Persist to `path`, creating parent directories.
    pub fn save(&self, path: &std::path::Path) -> Result<()> {
        self.validate()?;
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let text = serde_json::to_string_pretty(self)?;
        std::fs::write(path, text)?;
        Ok(())
    }

    pub fn save_default(&self, paths: &Paths) -> Result<()> {
        self.save(&paths.config_file())
    }

    /// Reject values that would break later stages of the pipeline.
    pub fn validate(&self) -> Result<()> {
        if self.install_timeout_secs == 0 {
            return Err(Error::Config {
                field: "install_timeout_secs".into(),
                reason: "must be greater than zero".into(),
            });
        }
        if !matches!(
            self.log_level.as_str(),
            "trace" | "debug" | "info" | "warn" | "error"
        ) {
            return Err(Error::Config {
                field: "log_level".into(),
                reason: format!(
                    "'{}' is not a tracing level (trace, debug, info, warn, error)",
                    self.log_level
                ),
            });
        }
        if self.allow_remote_registry {
            let url = self.registry_url.trim();
            if !(url.starts_with("https://") || url.starts_with("http://")) {
                return Err(Error::Config {
                    field: "registry_url".into(),
                    reason: "must be an http(s) URL".into(),
                });
            }
        }
        if let Some(WineVariant::Build(name)) = Some(self.wine_variant.clone()) {
            if name.trim().is_empty() {
                return Err(Error::Config {
                    field: "wine_variant".into(),
                    reason: "a named build must not be empty".into(),
                });
            }
        }
        Ok(())
    }

    /// Install timeout as a [`std::time::Duration`].
    pub fn install_timeout(&self) -> std::time::Duration {
        std::time::Duration::from_secs(self.install_timeout_secs)
    }

    /// The DXVK settings actually written and exported.
    ///
    /// The performance-mode preset is the starting point and the user's explicit
    /// values are applied on top, so switching mode never silently discards a
    /// hand-entered frame cap.
    pub fn effective_dxvk_settings(&self) -> DxvkSettings {
        let mut settings = self.performance_mode.preset();
        let explicit = &self.dxvk_settings;
        if !explicit.hud.is_empty() {
            settings.hud = explicit.hud.clone();
        }
        if explicit.max_frame_rate > 0 {
            settings.max_frame_rate = explicit.max_frame_rate;
        }
        if explicit.max_frame_latency > 0 {
            settings.max_frame_latency = explicit.max_frame_latency;
        }
        if explicit.compiler_threads > 0 {
            settings.compiler_threads = explicit.compiler_threads;
        }
        if explicit.sync_interval >= 0 {
            settings.sync_interval = explicit.sync_interval;
        }
        // The graphics pipeline library is the one setting the performance mode
        // exists to change, so the two combine rather than one overriding the
        // other: Compatibility always turns it off, and an explicit `false`
        // turns it off in any mode. Turning it back *on* from Compatibility is
        // deliberately not expressible — `true` is the field's default, so an
        // explicit `true` cannot be told apart from "not set", and honouring it
        // would make Compatibility mode a silent no-op for the setting it was
        // chosen for. Use Balanced or Performance to get the fast path.
        settings.graphics_pipeline_library =
            settings.graphics_pipeline_library && explicit.graphics_pipeline_library;
        settings
    }

    /// Resolve the paths this configuration implies.
    pub fn resolve_paths(&self) -> Result<Paths> {
        match &self.data_dir {
            Some(dir) if !dir.as_os_str().is_empty() => Ok(Paths::with_data_dir(dir)),
            _ => Paths::discover(),
        }
    }
}

#[cfg(test)]
mod tests {
    // Setting one field on a default is the clearest way to say "defaults,
    // except this"; the lint is aimed at production code, where it usually
    // means a missing derive.
    #![allow(clippy::field_reassign_with_default)]
    use super::*;

    #[test]
    fn defaults_are_safe_and_private() {
        let c = Config::default();
        assert!(!c.telemetry, "telemetry must be opt-in");
        assert_eq!(c.sandbox, SandboxMode::Strict);
        assert!(!c.prompt_for_main_exe);
        assert!(
            !c.install_silently,
            "showing an installer's own window is the safer default"
        );
        c.validate().unwrap();
    }

    #[test]
    fn round_trips_through_json() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("nested/config.json");
        let mut c = Config::default();
        c.dxvk = false;
        c.shared_folders.push(PathBuf::from("/home/u/Documents"));
        c.dxvk_settings.max_frame_rate = 60;
        c.save(&path).unwrap();

        let loaded = Config::load(&path).unwrap();
        assert_eq!(loaded, c);
    }

    #[test]
    fn missing_file_yields_defaults() {
        let tmp = tempfile::tempdir().unwrap();
        let loaded = Config::load(&tmp.path().join("nope.json")).unwrap();
        assert_eq!(loaded, Config::default());
    }

    #[test]
    fn corrupt_file_is_an_error_not_a_silent_reset() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("config.json");
        std::fs::write(&path, "{ not json").unwrap();
        assert!(Config::load(&path).is_err());
    }

    #[test]
    fn partial_json_fills_missing_fields_from_defaults() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("config.json");
        std::fs::write(&path, r#"{"dxvk": false}"#).unwrap();
        let c = Config::load(&path).unwrap();
        assert!(!c.dxvk);
        assert_eq!(c.install_timeout_secs, 3600);
        assert_eq!(c.wine_variant, WineVariant::Stable);
    }

    #[test]
    fn validation_rejects_bad_values() {
        let mut c = Config::default();
        c.install_timeout_secs = 0;
        assert!(matches!(c.validate(), Err(Error::Config { .. })));

        let mut c = Config::default();
        c.log_level = "chatty".into();
        assert!(c.validate().is_err());

        let mut c = Config::default();
        c.registry_url = "ftp://example.com/profiles.json".into();
        assert!(c.validate().is_err());

        // Disabling the registry means the URL is no longer validated.
        let mut c = Config::default();
        c.allow_remote_registry = false;
        c.registry_url = "not a url".into();
        c.validate().unwrap();
    }

    #[test]
    fn data_dir_override_wins_over_xdg() {
        let mut c = Config::default();
        c.data_dir = Some(PathBuf::from("/tmp/custom-windrop"));
        assert_eq!(
            c.resolve_paths().unwrap().data_dir(),
            std::path::Path::new("/tmp/custom-windrop")
        );

        c.data_dir = Some(PathBuf::new());
        assert_eq!(c.resolve_paths().unwrap(), Paths::discover().unwrap());
    }

    #[test]
    fn dxvk_settings_render_conf_and_env() {
        let mut s = DxvkSettings::default();
        s.max_frame_rate = 120;
        s.compiler_threads = 8;
        s.hud = "fps,devinfo".into();
        let conf = s.to_conf();
        assert!(conf.contains("d3d9.maxFrameRate = 120"));
        assert!(conf.contains("dxgi.maxFrameRate = 120"));
        assert!(conf.contains("dxvk.numCompilerThreads = 8"));
        assert!(conf.contains("dxvk.enableGraphicsPipelineLibrary = True"));

        let env = s.to_env();
        assert!(env.contains(&("DXVK_HUD".to_string(), "fps,devinfo".to_string())));
        assert!(env.contains(&("DXVK_FRAME_RATE".to_string(), "120".to_string())));
    }

    #[test]
    fn the_balanced_mode_is_exactly_the_defaults() {
        let config = Config::default();
        assert_eq!(config.performance_mode, PerformanceMode::Balanced);
        assert_eq!(config.effective_dxvk_settings(), DxvkSettings::default());
    }

    #[test]
    fn performance_and_compatibility_presets_differ_usefully() {
        let performance = PerformanceMode::Performance.preset();
        assert_eq!(
            performance.max_frame_latency, 1,
            "queue one frame for low latency"
        );
        assert!(performance.graphics_pipeline_library);

        let compatibility = PerformanceMode::Compatibility.preset();
        assert!(!compatibility.graphics_pipeline_library);
        assert_eq!(compatibility.sync_interval, 1, "vsync on for correctness");
        assert_ne!(performance, compatibility);
    }

    #[test]
    fn explicit_settings_survive_a_mode_change() {
        let mut config = Config::default();
        config.performance_mode = PerformanceMode::Performance;
        config.dxvk_settings.max_frame_rate = 144;
        config.dxvk_settings.hud = "fps".into();
        config.dxvk_settings.compiler_threads = 6;

        let effective = config.effective_dxvk_settings();
        assert_eq!(effective.max_frame_rate, 144, "the user's cap must win");
        assert_eq!(effective.hud, "fps");
        assert_eq!(effective.compiler_threads, 6);
        // ...while the preset still supplies what was not overridden.
        assert_eq!(effective.max_frame_latency, 1);

        config.performance_mode = PerformanceMode::Compatibility;
        let effective = config.effective_dxvk_settings();
        assert_eq!(effective.max_frame_rate, 144);
        assert!(!effective.graphics_pipeline_library);
    }

    #[test]
    fn a_mode_round_trips_through_json() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("config.json");
        let mut config = Config::default();
        config.performance_mode = PerformanceMode::Compatibility;
        config.save(&path).unwrap();
        assert_eq!(
            Config::load(&path).unwrap().performance_mode,
            PerformanceMode::Compatibility
        );
    }

    #[test]
    fn default_dxvk_settings_do_not_emit_unwanted_env() {
        let env = DxvkSettings::default().to_env();
        assert!(
            env.is_empty(),
            "defaults should not force any DXVK_* variable"
        );
        let conf = DxvkSettings::default().to_conf();
        assert!(!conf.contains("maxFrameRate"));
    }
}
